{% set name = "gammapy" %}
{% set version = "0.14" %}
{% set hash_type = "sha256" %}
{% set hash_value = "819565824ca67cf657154a458bf6fcddfb67e49494c87cc32aef9eb360f7fd9c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - gammapy = gammapy.scripts.main:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - pip
    - cython
    - numpy >=1.16
    - astropy >=3.2
  run:
    - python >=3.6
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2
    - astropy >=3.2
    - regions >=0.4
    - click >=7.0
    - pyyaml >=5.1
    - jsonschema >=3.0

test:
  imports:
    - gammapy
    - gammapy.astro
    - gammapy.astro.darkmatter
    - gammapy.astro.population
    - gammapy.astro.source
    - gammapy.catalog
    - gammapy.cube
    - gammapy.data
    - gammapy.detect
    - gammapy.irf
    - gammapy.maps
    - gammapy.modeling
    - gammapy.modeling.models
    - gammapy.scripts
    - gammapy.spectrum
    - gammapy.stats
    - gammapy.time
    - gammapy.utils
    - gammapy.utils.coordinates
    - gammapy.utils.random
  commands:
    - gammapy --help

about:
  home: https://gammapy.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A Python package for gamma-ray astronomy
  description: |
    Gammapy is an open-source Python package for gamma-ray astronomy built on Numpy and Astropy. 
    It is a prototype for the Cherenkov Telescope Array (CTA) science tools,
    and can also be used to analyse data from existing gamma-ray telescopes.
  doc_url: https://docs.gammapy.org/
  dev_url: https://github.com/gammapy/gammapy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - cdeil
    - adonath
    - registerrier
