{% set name = "gammapy" %}
{% set version = "0.13" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e0d3135c4ac9e68f3f57862c56285c59477889a4d9b3b7e85ab1dcf31dab169b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: true  # [py27]
  entry_points:
    - gammapy = gammapy.scripts.main:cli
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - astropy >=2.0
  run:
    - python
    - numpy >=1.8
    - scipy
    - astropy >=2.0
    - regions
    - click
    - pyyaml

test:
  imports:
    - gammapy
    - gammapy.astro
    - gammapy.astro.darkmatter
    - gammapy.astro.population
    - gammapy.astro.source
    - gammapy.background
    - gammapy.catalog
    - gammapy.cube
    - gammapy.cube.models
    - gammapy.data
    - gammapy.detect
    - gammapy.extern
    - gammapy.image
    - gammapy.image.models
    - gammapy.irf
    - gammapy.maps
    - gammapy.scripts
    - gammapy.spectrum
    - gammapy.spectrum.models
    - gammapy.stats
    - gammapy.time
    - gammapy.time.models
    - gammapy.utils
    - gammapy.utils.coordinates
    - gammapy.utils.distributions
    - gammapy.utils.fitting
  commands:
    - gammapy --help

about:
  home: https://gammapy.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A Python package for gamma-ray astronomy
  description: |
    Gammapy is an open-source Python package for gamma-ray astronomy built on Numpy and Astropy. 
    It is a prototype for the Cherenkov Telescope Array (CTA) science tools,
    and can also be used to analyse data from existing gamma-ray telescopes.
  doc_url: https://docs.gammapy.org/
  dev_url: https://github.com/gammapy/gammapy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - cdeil
    - adonath
    - registerrier
