travis:
  secure:
    BINSTAR_TOKEN: eE4O/jJDMmpuqvl2ZupdLrVZQa4s4a6HhOlAJ58G77nHbdre/ydvVlaO3RZsPjazR+R0cEQfSfXLnZXMHzVUf+01MN7g75XMVM8rjBE+Wi9ZS3U3EEU5MyMjz58d2ivpzICYs2h0XWsIboHlOnDS4WqLF4KtRMdKYNejhEBKMQGSjDTs+Z3DAFhfCWynTgr+BwQjRI1v47fjQGUsQ4YENJyI6J554AcWNH0A+wX+mqbQ4l5i1oZcR1sNNb1zOAgt+0T0Is5Ja6x9j+3qbhy9eJ4v84Oe7YtQjhmlkn0mPZHnD6vDlN6D7YUaYH3s4dEDvS/T9f98jfzuV3ESTzm0Hn1fJqXFlxicn8j6pUYYwPHeQUSHrZpOf3+ZYOZiRWsMk1e1YDUEFXe9kcrhYr8AUX9nclm/4JQKha3rsys4ZVSKLyXzzCph5vKLFxpkL8uWHpMs92RNNYo54Yby3CEj7rgIznGX/nrMnNubLXpWShL62LcREkT55HZV440KZv4g2OgTiRZhEoFc40xo6CHoiFCTjS9FTzBRyIjUq2qj6ehDKieOjbbM/5y7AWYX/cFtSIaap2CKa8V+TLr4SgLmqUF7MDrLOvbmg3Is+ZDIixdmb3+Sfg5Iu8JztuaqDJRNiV0L8RMGV1A/y0BZ82YzlPa8BgMvkH3Rfx67wqjG8qU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
